CREATE sequence ORDER_REPOSITORY_SEQ;
CREATE sequence ORDER_POSITION_SEQ;


create table ORDER_REPOSITORY
(
    ID         BIGINT auto_increment
        primary key,
    ID_USER   BIGINT not null,
    All_SUM    DECIMAL(20,2)  not null,
    STATUS     VARCHAR(10) default ('CREATED')
        check (STATUS IN ('BUY', 'CLOSED', 'CREATED')) ,
    DATA_CREATED    TIMESTAMP,
    DATA_CLOSED TIMESTAMP
);

create table ORDER_POSITION
(
    ID               BIGINT auto_increment
        primary key,
    ID_PRODUCT       BIGINT not null,
    ID_ORDER_REPOSITORY BIGINT not null,
    QUANTITY           INT        not null,
    SUM              DECIMAL(15,2) not null
);



ALTER TABLE ORDER_REPOSITORY  ADD FOREIGN KEY (ID_USER) REFERENCES USERS(ID);
ALTER TABLE ORDER_POSITION  ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID);
ALTER TABLE ORDER_POSITION  ADD FOREIGN KEY (ID_ORDER_REPOSITORY) REFERENCES ORDER_REPOSITORY(ID);

COMMIT;