
package com.accenture.flowershop.fe.ws.ClientWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlowersStockWebService", targetNamespace = "http://ws.fe.flowershop.accenture.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlowersStockWebService {


    /**
     * 
     * @param request
     */
    @WebMethod
    @RequestWrapper(localName = "increaseFlowersStockSize", targetNamespace = "http://ws.fe.flowershop.accenture.com/", className = "com.accenture.flowershop.fe.ws.ClientWS.IncreaseFlowersStockSize")
    @ResponseWrapper(localName = "increaseFlowersStockSizeResponse", targetNamespace = "http://ws.fe.flowershop.accenture.com/", className = "com.accenture.flowershop.fe.ws.ClientWS.IncreaseFlowersStockSizeResponse")
    public void increaseFlowersStockSize(
        @WebParam(name = "request", targetNamespace = "")
        int request);

}
