
package com.accenture.flowershop.fe.ws.ClientWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlowersStockWebServiceImplService", targetNamespace = "http://ws.fe.flowershop.accenture.com/", wsdlLocation = "http://localhost:8080/flowershop/ws/FlowersStockWebService?wsdl")
public class FlowersStockWebServiceImplService
    extends Service
{

    private final static URL FLOWERSSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLOWERSSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FLOWERSSTOCKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.fe.flowershop.accenture.com/", "FlowersStockWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/flowershop/ws/FlowersStockWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLOWERSSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FLOWERSSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FlowersStockWebServiceImplService() {
        super(__getWsdlLocation(), FLOWERSSTOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FlowersStockWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLOWERSSTOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FlowersStockWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FLOWERSSTOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FlowersStockWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLOWERSSTOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FlowersStockWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlowersStockWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlowersStockWebService
     */
    @WebEndpoint(name = "FlowersStockWebServiceImplPort")
    public FlowersStockWebService getFlowersStockWebServiceImplPort() {
        return super.getPort(new QName("http://ws.fe.flowershop.accenture.com/", "FlowersStockWebServiceImplPort"), FlowersStockWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlowersStockWebService
     */
    @WebEndpoint(name = "FlowersStockWebServiceImplPort")
    public FlowersStockWebService getFlowersStockWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.fe.flowershop.accenture.com/", "FlowersStockWebServiceImplPort"), FlowersStockWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLOWERSSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FLOWERSSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FLOWERSSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
